name: Main CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  frontend-build:
    uses: rknaik76/build-test/.github/workflows/fe-build.yaml@v3.0.0
    with:
      target_branch: main
      environment: production
      artifact_name: front-end-${{ github.run_id }}.zip

  backend-build:
    uses: rknaik76/build-test/.github/workflows/be-build.yaml@v3.0.0
    with:
      target_branch: main
      environment: production
      artifact_name: back-end-${{ github.run_id }}.zip

  sonarqube-heavy-scan:
    uses: rknaik76/build-test/.github/workflows/sonarqube.yaml@v3.0.0
    with:
      target_branch: main
      environment: production
      scan_type: heavy
    secrets:
      sonar_project_key: ${{ secrets.SONARQUBE_PROJECT_KEY }}
      sonar_organization: ${{ secrets.SONARQUBE_ORGANIZATION }}

  veracode-scan-frontend:
    uses: rknaik76/build-test/.github/workflows/veracode-scan.yaml@v3.0.0
    needs: [frontend-build]
    with:
      target_branch: main
      environment: production
      artifact_name: front-end-${{ github.run_id }}.zip
    secrets:
      veracode_app_id: ${{ secrets.VERACODE_APP_ID }}
      veracode_app_name: ${{ secrets.VERACODE_APP_NAME }}
      veracode_api_key_id: ${{ secrets.VERACODE_API_KEY_ID }}

  veracode-scan-backend:
    uses: rknaik76/build-test/.github/workflows/veracode-scan.yaml@v3.0.0
    needs: [backend-build]
    with:
      target_branch: main
      environment: production
      artifact_name: back-end-${{ github.run_id }}.zip
    secrets:
      veracode_app_id: ${{ secrets.VERACODE_APP_ID }}
      veracode_app_name: ${{ secrets.VERACODE_APP_NAME }}
      veracode_api_key_id: ${{ secrets.VERACODE_API_KEY_ID }}

  # front-end-deployment:
  #   name: Frontend Deployment
  #   needs: [veracode-scan-frontend, sonarqube-heavy-scan, call-frontend-build]
  #   # uses: ./.github/workflows/deployment.yaml # Adjust branch if needed
  #   uses: rknaik76/build-test/.github/workflows/deployment.yaml@v3.0.0
  #   with:
  #     target_branch: main
  #     environment: production
  #     artifact_name: "front-end-artifact"
  #     webapp_name: "my-frontend-webapp"

  # back-end-deployment:
  #   name: Backend Deployment
  #   needs: call-build-test
  #   uses: rknaik76/build-test/.github/workflows/deployment.yaml@v3.0.0 # Adjust branch if needed
  #   with:
  #     target_branch: main
  #     environment: production
  #     artifact_name: "backend-artifact"
  #     webapp_name: "my-backend-webapp"
