name: Main CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  frontend-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Front-end Linting
        run: echo "Installing frontend dependencies..."

  sonarqube-front-end:
    uses: rknaik76/build-test/.github/workflows/sonarqube.yaml@v5.0.0
    needs: [frontend-linting]
    with:
      target_branch: main
      environment: production
      scan_type: heavy
    secrets:
      sonar_project_key: ${{ secrets.SONARQUBE_PROJECT_KEY }}
      sonar_organization: ${{ secrets.SONARQUBE_ORGANIZATION }}

  frontend-build:
    uses: rknaik76/build-test/.github/workflows/fe-build.yaml@v5.0.0
    needs: [sonarqube-front-end]
    with:
      target_branch: main
      environment: production
      artifact_name: front-end-${{ github.run_id }}.zip

  backend-build:
    uses: rknaik76/build-test/.github/workflows/be-build.yaml@v5.0.0
    with:
      target_branch: main
      environment: production
      artifact_name: back-end-${{ github.run_id }}.zip

  sonarqube-back-end:
    uses: rknaik76/build-test/.github/workflows/sonarqube.yaml@v5.0.0
    needs: [backend-build]
    with:
      target_branch: main
      environment: production
      scan_type: heavy
    secrets:
      sonar_project_key: ${{ secrets.SONARQUBE_PROJECT_KEY }}
      sonar_organization: ${{ secrets.SONARQUBE_ORGANIZATION }}

  upload-backend-artifact:
    name: Upload Backend Artifact
    needs: [backend-build, sonarqube-back-end]
    runs-on: ubuntu-latest
    steps:
      - name: Download Backend Artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-artifact

  # veracode-scan-frontend:
  #   uses: rknaik76/build-test/.github/workflows/veracode-scan.yaml@v5.0.0
  #   needs: [frontend-build]
  #   with:
  #     target_branch: main
  #     environment: production
  #   secrets:
  #     veracode_app_id: ${{ secrets.VERACODE_APP_ID }}
  #     veracode_app_name: ${{ secrets.VERACODE_APP_NAME }}
  #     veracode_api_key_id: ${{ secrets.VERACODE_API_KEY_ID }}
  #     veracode_api_key_secret: ${{ secrets.VERACODE_API_KEY_SECRET }}

  # veracode-scan-backend:
  #   uses: rknaik76/build-test/.github/workflows/veracode-scan.yaml@v5.0.0
  #   needs: [backend-build]
  #   with:
  #     target_branch: main
  #     environment: production
  #   secrets:
  #     veracode_app_id: ${{ secrets.VERACODE_APP_ID }}
  #     veracode_app_name: ${{ secrets.VERACODE_APP_NAME }}
  #     veracode_api_key_id: ${{ secrets.VERACODE_API_KEY_ID }}
  #     veracode_api_key_secret: ${{ secrets.VERACODE_API_KEY_SECRET }}

  # front-end-deployment:
  #   name: Frontend Deployment
  #   needs: [veracode-scan-frontend, sonarqube-heavy-scan, call-frontend-build]
  #   # uses: ./.github/workflows/deployment.yaml # Adjust branch if needed
  #   uses: rknaik76/build-test/.github/workflows/deployment.yaml@v5.0.0
  #   with:
  #     target_branch: main
  #     environment: production
  #     artifact_name: "front-end-artifact"
  #     webapp_name: "my-frontend-webapp"

  # back-end-deployment:
  #   name: Backend Deployment
  #   needs: call-build-test
  #   uses: rknaik76/build-test/.github/workflows/deployment.yaml@v5.0.0 # Adjust branch if needed
  #   with:
  #     target_branch: main
  #     environment: production
  #     artifact_name: "backend-artifact"
  #     webapp_name: "my-backend-webapp"
