name: Main CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  call-build-test:
    # uses: ./.github/workflows/pr-validation.yaml # Adjust branch if needed
    uses: rknaik76/build-test/.github/workflows/ci.yaml@v2.0.0
    with:
      target_branch: main
      environment: production

  front-end-deployment:
    name: Frontend Deployment
    needs: call-build-test
    # uses: ./.github/workflows/deployment.yaml # Adjust branch if needed
    uses: rknaik76/build-test/.github/workflows/deployment.yaml@v2.0.0
    with:
      target_branch: main
      environment: production
      artifact_name: "front-end-artifact"
      webapp_name: "my-frontend-webapp"

  back-end-deployment:
    name: Backend Deployment
    needs: call-build-test
    uses: rknaik76/build-test/.github/workflows/deployment.yaml@v2.0.0 # Adjust branch if needed
    with:
      target_branch: main
      environment: production
      artifact_name: "backend-artifact"
      webapp_name: "my-backend-webapp"
