name: PR Validation Pipeline

on:
  pull_request:
    branches:
      - main
      - release/*
      - feat/*

jobs:
  call-build-test:
    uses: rknaik76/build-test/.github/workflows/ci.yaml@v2.0.0
    with:
      target_branch: main
      environment: pr-validate
