name: Rollback Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to rollback"
        required: true
        type: choice
        options:
          - development
          - staging
          - production
      version:
        description: "Enter the semantic version (e.g., 1.4.0 or 2.1.3+9826)"
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Show rollback inputs
        run: |
          echo "Rollback requested for environment: ${{ github.event.inputs.environment }}"
          echo "Rollback to version: ${{ github.event.inputs.version }}"
